apiVersion: v1
kind: Secret
metadata:
  name: truetrace-secrets
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  truetrace-security-sync-token: {{ .Values.secrets.truetraceSecuritySyncToken | b64enc | quote }}
  dashscope-api-key: {{ .Values.secrets.dashscopeApiKey | b64enc | quote }}
  htpasswd: {{ .Files.Get "configs/.htpasswd" | b64enc | quote }}
