apiVersion: v1
kind: Secret
metadata:
  name: truetrace-secrets
type: Opaque
data:
  postgres-password: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | b64enc | quote }}
  truetrace-security-sync-token: {{ required "secrets.truetraceSecuritySyncToken is required" .Values.secrets.truetraceSecuritySyncToken | b64enc | quote }}
  dashscope-api-key: {{ required "secrets.dashscopeApiKey is required" .Values.secrets.dashscopeApiKey | b64enc | quote }}
  htpasswd: {{ .Files.Get "configs/.htpasswd" | b64enc | quote }}
