apiVersion: v2
name: truetrace-platform
description: Helm chart for the TrueTrace Multi-Agent Deepfake and AML Compliance Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - security
  - banking
  - aml
  - deepfake
  - compliance
home: https://github.com/Little-Boy-s-TrueTrace/truetrace
sources:
  - https://github.com/Little-Boy-s-TrueTrace/truetrace-deployment
